name: XCS234_A3_GPU
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.4.5
  - tk>=8.6.8
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - scipy=1.6.2
  - tensorboard=2.10.1
  - pyyaml=6.0
  - pytorch==1.11.0
  - pip=22.1.2
  - pip:
    - matplotlib==3.5.2
    - imageio==2.19.3
    - numpy==1.23.1
    - pygame==2.1.2
    - mujoco==2.1.2
    - dm-control==1.0.0
    - gym==0.26.2
